version: '2'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    image: yzhang/jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home